# Generated by Django 3.2.6 on 2022-01-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('item_qty', models.IntegerField()),
                ('store', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('specs', models.CharField(max_length=300)),
                ('costPrice', models.CharField(max_length=50)),
                ('srp', models.CharField(max_length=50)),
                ('benerson_qty', models.IntegerField()),
                ('qlinx_qty', models.IntegerField()),
                ('receipts', models.ManyToManyField(to='inventory.Receipt')),
            ],
        ),
    ]
