# Generated by Django 3.2 on 2024-07-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_receipt_quantities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='receipts',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='quantities',
        ),
        migrations.CreateModel(
            name='ItemInReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.receipt')),
            ],
        ),
    ]
