# Generated by Django 3.2 on 2024-07-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20240725_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='total_price',
            field=models.CharField(default='0.00', max_length=15),
        ),
    ]
