# Generated by Django 3.2 on 2024-07-29 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_receipt_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255, null=True)),
                ('barangay', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=75)),
                ('province', models.CharField(max_length=75)),
                ('region', models.CharField(max_length=15)),
                ('demographic', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.customer'),
        ),
    ]
