# Generated by Django 3.2 on 2024-08-01 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20240729_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount_paid',
            field=models.CharField(default='0.00', max_length=15),
        ),
        migrations.AlterField(
            model_name='iteminreceipt',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='store',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ReceiptInReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_receipt', to='inventory.receipt')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_document', to='inventory.receipt')),
            ],
        ),
    ]
