# Generated by Django 3.2 on 2024-08-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20240801_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptinreceipt',
            name='amount_paid',
            field=models.CharField(default='0.00', max_length=15),
        ),
    ]
